grafanaVolume:
  name: "grafana-volume"
  size: "256Mi"
  accessMode: "ReadWriteMany"
  mountPath: "/data/grafana/"
  # The name of the node is quite important, w/o it
  # We'll encounter a "no nodes assigned err"
  nodeName: "minikube"
  storageClassName: "grafana-volume"

postgresVolume:
  name: "postgres-volume"
  size: "256Mi"
  accessMode: "ReadWriteMany"
  mountPath: "/data/database/"
  # The name of the node is quite important, w/o it
  # We'll encounter a "no nodes assigned err"
  nodeName: "minikube"

  # The storageclasses can be shared, no biggie but, 
  # maybe a better idea to seperate these.
  storageClassName: "postgres-volume"
