apiVersion: v1
kind: Service 
metadata:
  name: {{  .Values.grafana.serviceName  }}
  namespace: {{ .Values.grafana.namespace }}
spec:
  selector:
    app: {{  .Values.grafana.appName  }}
  ports:
    - name: grafana-port
      protocol: TCP
      port: 80
      targetPort: 3000

  type: ClusterIP
