apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.name }}
  namespace: {{ .Values.grafana.namespace }}
spec:
  accessModes:
    - {{ .Values.volume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.volume.requiredStorage }}
  storageClassName: {{ .Values.volume.storageClassName }}
