apiVersion: v1
kind: Service 
metadata:
  name: {{  .Values.postgres.serviceName  }}
  namespace: {{ .Values.postgres.namespace }}
spec:
  selector:
    app: {{  .Values.postgres.appName  }}
  ports:
    - name: postgres-port
      protocol: TCP
      port: 80
      targetPort: 5432

  type: ClusterIP
