apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.postgressVolume.name }}
spec:
  capacity:
    storage: {{ .Values.postgressVolume.size }}
  accessModes:
    - {{ .Values.postgressVolume.accessMode }}
  persistentVolumeReclaimPolicy: Retain

  # local: We'd rather use the `hostPath` instead of `local` for this 
  # particular PersistentVolume, since, I'd rather store the files 
  # in my host Device instead of putting strain on minikube's 
  # storage provisioner
  hostPath:
    path: {{ .Values.postgressVolume.mountPath }}

  storageClassName: {{ .Values.postgressVolume.storageClassName }}

  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.postgressVolume.nodeName }} # We need to make sure we're using postgressVolume within a specified node.
