apiVersion: v1
kind: Service 
metadata:
  name: {{  .Values.prefect.serviceName  }}
  namespace: {{ .Values.prefect.namespace }}
spec:
  selector:
    app: {{  .Values.prefect.appName  }}
  ports:
    - name: prefect-port
      protocol: TCP
      port: 80
      targetPort: 4200

  type: ClusterIP
