postgres:
  deploymentName: "postgres-deployment"
  namespace: "databases"
  replicas: 1
  appName: "postgres-app"
  imageName: "postgres"
  imageVersion: "17-bookworm"
  cpuLimit: "500m"
  memoryLimit: "512Mi"
  cpuRequest: "100m"
  memoryRequest: "32Mi"
  password: "123#password"
  serviceName: "postgres-service"

volume:
  name: "postgres-claim"
  namespace: "databases"
  accessMode: "ReadWriteMany"
  requiredStorage: "128Mi"
  storageClassName: "postgres-volume"

configMap:
  name: "postgres-configmap"

ingress:
  name: "postgres-ingress"
  timeout: "600000"
